# Generated by Django 3.1.4 on 2021-03-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expanse',
            new_name='Expense',
        ),
    ]
